<a href="https://colab.research.google.com/github/daiju0722/Deeplearning2022Late/blob/main/NumPyReplay2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPyを使用する

In [1]:
import numpy as np

### 配列（アレイ）を作る

In [4]:
x=np.array([1.0,2.0,3.0,4.0,5.0])
print(x)
# array()は、Pythonのリストを渡すことでNumPy用の配列(numpy.ndarray)を生成します。

x=np.array([1,2,3])
print(x) 
print(type(x))

my_list1=[1,2,3,4,5]
my_array1=np.array(my_list1)

my_list2=[1020,30,40,50]
my_lists=[my_list1,my_list2]
my_lists

my_array2=np.array(my_lists)

my_array2


[1. 2. 3. 4. 5.]
[1 2 3]
<class 'numpy.ndarray'>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  app.launch_new_instance()


array([list([1, 2, 3, 4, 5]), list([1020, 30, 40, 50])], dtype=object)

### NumPy配列の形状を調べる

In [6]:
a=np.array([1,2,3,4])
a.shape
b=np.array([[1,2],[3,4]])
b.shape

(2, 2)

### 配列の生成arange()

In [7]:
#データの準備
#等間隔の数字
#０から９までの数字（配列）を生成
x=np.arange(10)
print(x)

#reshape()は配列を計上に変換します。
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,10).reshape(3,3)

print(x)
print(y)

print(x+y)
print(x-y)
print(x*y)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 配列操作

In [8]:
sample_array=np.arange(10)
print(sample_array)


sample_array2=sample_array.reshape(2,5)
print(sample_array2)

sample_array3=np.array([[1,2,3],[4,5,6]])
sample_array4=np.array([[7,8,9],[10,11,12]])

print(np.concatenate([sample_array3,sample_array4],axis=1))

print(np.hstack((sample_array3,sample_array4)))


print(np.concatenate([sample_array3,sample_array4],axis=0))

print(np.vstack((sample_array3,sample_array4)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### ブロードキャスト
ブロードキャストは、配列の大きさが異なっていれば、自動的に要素をコピーし大きさをそろえるNumPyの機能です。

In [9]:
#データの準備
sample_array=np.arange(10)
print(sample_array)

print(sample_array+5)


[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


### 多次元配列の計算

In [10]:
n1=np.array([1,2,3,4,5])
print(n1)

np.ndim(n1)

n1.shape

n2=np.array([[1,2],[3,4],[5,6]])
print(n2)

print(n2.ndim)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
2


### 行列とは
行列は、数や記号、式などを行と列に沿って配列したものです。数学の線形代数学周辺分野で出てきます。

In [11]:
my_li1=[-1,4]
my_li2=[3,2]
my_li3=[2,5]
my_li4=[0,1]
my_lists=[my_li1,my_li2,my_li3,my_li4]
my_array3=np.array(my_lists)

my_array3

array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])