<a href="https://colab.research.google.com/github/daiju0722/Deeplearning2022Late/blob/main/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%A8%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E4%BD%BF%E7%94%A80920.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# モジュールを使う
## import文でモジュールを読み込んで使う
例) math


In [29]:
# math モジュールを読み込む
import math as mt
print(mt.pi) # mathの中に定義してある円周率を表示
print(mt.pow(5, 2)) # ５の２乗
print(mt.sqrt) # ９の平方根

3.141592653589793
25.0
<built-in function sqrt>


## Numpy-数値計算用の便利なライブラリ
https://numpy.org/

In [30]:
# numpy をimport
import numpy as np

### numpy配列を作る(ndarray)

In [31]:
a = np.array([5, 7, 3, 1, 4, 3])
print(a)

[5 7 3 1 4 3]


## Numpyで配列の操作をしてみる
### 配列を構成しなおす

In [32]:
# 現在、aは１行１次元配列
print(a)
# aを３行２列の２次元配列に構成しなおす
b = a.reshape([3, 2]) # 新しい配列の構成を引数で指定する
print(b)

[5 7 3 1 4 3]
[[5 7]
 [3 1]
 [4 3]]


## Numpy配列の中身を初期化して作る

In [33]:
# ３行４列の０が入った２次元配列を作る
np.zeros([3, 4])
# ランダムな値が入った配列を作る
np.random.seed(0)
r = np.random.rand(3, 4)
print(r)

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


## Numpyのスライスのやり方
### 基本
スライスの指定の仕方[start : stop : step]で指定する

In [34]:
# リストのスライス
l = list(range(10)) # ０～９までの１０個の要素のリスト
print(l)
print(l[4:8])#[4:8]でスライス
print(l[ : : -1]) # stepを-1でスライス

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


## １次元のNumpy配列(ndarray)におけるスライス

In [35]:
# 範囲を指定してndarrayを作る
a = np.arange(10)
print(a)
print(a[2:8])
print(a[2:8:2]) # step2で２個飛ばし
print(a[2:8:3]) #step3で３個飛ばし

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6]
[2 5]


## １次元配列のndarrayのスライスに代入

In [36]:
print(a)
a[3:6] = 100 # 指定した範囲に特定の値を代入
print(a)
a[3:6] = [100, 200, 300] # 指定した範囲にリストの値を代入
print(a)
# a[3:6] = [100, 200, 300, 400] # 3つの範囲を４つの要素で上書きする
a = np.arange(10)
print(a)
a[2:8:2] = 100 # start2stop8にstep2で上書き
print(a)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100   6   7   8   9]
[  0   1   2 100 200 300   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1 100   3 100   5 100   7   8   9]


## 多次元配列のndarrayのスライス

In [37]:
# ３行４列の２次元配列を作る
a = np.arange(12).reshape((3, 4))
print(a)
# ２行目から終わりまでの行 = [1 : ]
# １列目から３列目手前までの列 = [ 1:3 ]
print(a[1: , 1:3])
b = np.arange(20).reshape(5,4)
print(b)
# 9,10,13,14,17,18の３行２列だけ抜き出す
print(b[2: , 1:3])
c = b[2: , 1:3]
print(c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 9 10]
 [13 14]
 [17 18]]
(3, 2)


## 多次元のndarrayへのスライスでの代入

In [38]:
# 要素数１２の３行４列の２次元配列を作る
a = np.arange(12).reshape(3,4)
print(a)
#5,6,9,10
b = a[1: , 1:3]
print(b)
a[1: , 1:3] = 100
print(a)
a = np.arange(12).reshape(3,4)
#多次元での上書きにリストを使う
a[1: ,1:3] =[ [100,200] , [300,400] ]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 300 400  11]]


### 多次元のndarrayへのstepを使ったスライスでの代入

In [39]:
# 要素数１２　３行４列のndarrayを作って変数aに代入
a = np.arange(12).reshape(3,4)
print(a)
# スライスにstepを使ってみる
print(a[1: , ::2])
#0,3,4,7抜き出す
print(a[:2: , ::3])
a[1: ,::2] = 100 # 4,6,8,10だったところを100で上書き
print(a)
a[1: ,::2] = [100,200]
print(a)
# 4,6,8,10だったところを多次元のリストで上書き
a[1: , ::2] = [[100,200],[300,400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]
[[0 3]
 [4 7]]
[[  0   1   2   3]
 [100   5 100   7]
 [100   9 100  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [100   9 200  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [300   9 400  11]]
